GENRE_NAME_MAX_LENGTH = 200
LANGUAGE_NAME_MAX_LENGTH = 200
BOOK_TITLE_MAX_LENGTH = 200
BOOK_SUMMARY_MAX_LENGTH = 1000
BOOK_ISBN_MAX_LENGTH = 13
BOOKINSTANCE_IMPRINT_MAX_LENGTH = 200
AUTHOR_FIRST_NAME_MAX_LENGTH = 100
AUTHOR_LAST_NAME_MAX_LENGTH = 100

LOAN_STATUS = (
    ('m', 'Maintenance'),
    ('o', 'On loan'),
    ('a', 'Available'),
    ('r', 'Reserved'),
)
